# Basic
title: å¼ å¤æ¥ 
user: zhangkn
subtitle: ä¸ªäººç«™
description: zhang kunnan's Personal Website
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: zhangkn
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: iOSre / Anti
url: "https://zhangkn.github.io"

# Comment
comment:
    disqus: iosre
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    weibo: 602056727 
    github: zhangkn
    twitter: zhangkunnan
    mail: zhang_kn@icloud.com
    gplus: 114188876079505437133

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: e7f6d46714fcd28fb24be011203bee5f  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-111030597-1
    host: auto  

Params: 
    Search: ç«™å†…æœç´¢

# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://zhangkn.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
plugins: [jekyll-paginate,jekyll-sitemap,jekyll-feed]
paginate: 20
paginate_path: "page/:num/"


